export const SET_WS_OPEN = 'SET_WS_OPEN';
export const SET_READER_STATUS = 'SET_READER_STATUS';
export const SET_SYSTEM_ID = 'SET_SYSTEM_ID';
export const SET_FIRMWARE_VERSION = 'SET_FIRMWARE_VERSION';
export const CLEAR_READER_STATUS = 'CLEAR_READER_STATUS';
export const SET_WIFI_STATUS = 'SET_WIFI_STATUS'

export const SET_RECENT_DATA  = 'SET_RECENT_DATA'
export const FORGET_WIFI_NETWORK = 'FORGET_WIFI_NETWORK'
export const SET_WIFI_NETWORKS = 'SET_WIFI_NETWORKS'

export const SET_CONFIRM_DIALOG = 'SET_CONFIRM_DIALOG'