export const SET_WS_OPEN = 'SET_WS_OPEN';
export const SET_READER_STATUS = 'SET_READER_STATUS';
export const SET_SYSTEM_ID = 'SET_SYSTEM_ID';
export const SET_FIRMWARE_VERSION = 'SET_FIRMWARE_VERSION';